/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cyberDestinationUtilityFactoryFacetSol from "./CyberDestinationUtilityFactoryFacet.sol";
export type { cyberDestinationUtilityFactoryFacetSol };
